CONTRIBUTING.md, LICENSE, README.md, code-of-conduct.md
Readme, License, COC, Contributing files.
=> documentation and readme.

Gemfile, Gemfile.lock, app/models/partner.rb, spec/factories/partner_factory.rb, spec/models/partner_spec.rb, spec/rails_helper.rb
=> Adding FactoryBot to the project with a test example

app/controllers/api/v1/partners_controller.rb, app/models/partner.rb, spec/requests/api/v1/partners_requests_spec.rb
=> render a nested partner structure

app/controllers/partners_controller.rb, app/models/partner.rb, app/services/diaper_bank_client.rb, app/views/partners/show.html.erb, config/initializers/devise.rb, config/initializers/mail_setup.rb, config/routes.rb
=> More feature spiking for national conf

db/seeds.rb
This PR adds some seeds for local development.
=> adds a couple of partners in seeds, approved and pending

spec/requests/api/v1/partners_requests_spec.rb
While it doesn't fully close it, this helps close #31  
Adds specs for testing the POST/create action of `Api::V1::PartnersController`.
Tests:
- Making a request with an empty body
- Make requests with a valid body
Tests
This PR only includes tests.
=> Adds request specs for the Partners API endpoint.

app/models/partner_request.rb, app/services/diaper_bank_client.rb, spec/models/item_spec.rb, spec/models/partner_request_spec.rb, spec/services/diaper_bank_client_spec.rb
* Non-breaking changes: Add specs and refactor method.
=> Refactor on model and services

spec/controllers/partners_controller_spec.rb
- I have added tests to partner controller
Resolves partially #31  
I have added test to partner controller for the methods create, approve and delete
=> add tests to partner controller

app/controllers/static_controller.rb, public/400.html, spec/controllers/static_controller_spec.rb
Resolves #49  
I've used %r{[^\w\-\/]+$} regex instead of /^[A-Za-z0-9_\-]+$/ because  \w = A-Za-z0-9_
added static_controller_spec.rb
=> Check the `:page` action for possible URL injection

app/models/partner_request.rb, spec/models/partner_request_spec.rb
@armahillo @seanmarcia this PR will help unblock a student's failing test on https://github.com/loyno-mathcs/partner/pull/7
=> Validate items when validating a partner request

spec/controllers/static_controller_spec.rb
Resolves #105  
Added one missing test.
Ran RSpec.
=> Added get:index test to static controller

app/views/children/new.html.erb
=> Fix new child process.

app/models/partner_request.rb
Cherrypicked from https://github.com/loyno-mathcs/partner/pull/20
=> Br cherrypick 111

README.md
Resolves #001 
Fix ruby version in readme.
n/a
=> Update rubyversion in docs to actual version

config/initializers/devise.rb
Resolves #93
Cherry Picking over commits from Loyola fork
=> Make invites never expire

spec/factories/families.rb, spec/features/add_child_to_family_feature_spec.rb, spec/features/authorized_family_member_feature_sepc.rb, spec/features/authorized_family_member_feature_spec.rb
=> Add tests to authorized family members

README.md, app/controllers/partners_controller.rb
Resolves #001 
- update ruby version to gemfile version
- fix typo in test login
n/a
=> Update README: ruby version, typo

app/controllers/authorized_family_members_controller.rb, app/controllers/children_controller.rb, app/controllers/families_controller.rb, app/controllers/partners_controller.rb
Resolves #001 
Issue 50:  Remove all json endpoints that are not in the `API::` namespace
=> Remove all json endpoints that are not in the api

.gitignore, Gemfile, Gemfile.lock, spec/rails_helper.rb
Working on Test coverage. This installs Simplecov for coverage reports. 
I wonder if there's a way to save the coverage artifacts on Travis. 
=> adds simplecov

README.md, bin/setup, bin/update, ubuntu-installation.md
Add more detailed information about installing the software on Ubuntu Linux.
=> Add 'ubuntu-installation.md' file.

.travis.yml, ci/deploy-production.sh
=> adding production ci script

README.md
Resolves #001 
add test and yarn sections from the diaper readme into partner readme
=> add test and yarn sections from the diaper readme into partner readme

app/views/partners/show.html.erb, config/locales/en.yml
Added "Not Provided" for fields with missing information on Organization Details page.
=> #156 Added "Not Provided" for fields with missing information.

app/controllers/api/v1/partners_controller.rb, app/models/user.rb, app/views/devise/mailer/invitation_instructions.html.erb, config/routes.rb
This goes along with the `customized_invitation` branch on the diaper side.
This PR allows diaper banks to add in their own custom messages when inviting partners to partnerbase.
=> customized invitation

app/views/layouts/_footer.html.erb, app/views/layouts/_navbar.html.erb, app/views/layouts/_sidebar.html.erb, app/views/layouts/application.html.erb
Fixed a bug when trying to log out through the navbar Logout button.
=> Bugfix logout button

config/routes.rb, spec/requests/static_request_spec.rb
Resolves #172  
I just moved the file `static_controller_spec` to `static_request_spec`. I made the necessary changes and I add a prefix (static_page_path) to `static/pages` to `routes.rb` file
* Improvement (?)
All the tests were green.
=> 172 migrate static controller spec to request spec

spec/rails_helper.rb, spec/requests/families_spec.rb
Resolves #150  
New specs to test Families Controller requests, improving test coverage
* Improvement
Running specs
=> test request for families controller

.rubocop.yml, app/controllers/children_controller.rb, app/views/children/_child.json.jbuilder, app/views/children/edit.html.erb, app/views/children/index.html.erb, app/views/children/index.json.jbuilder, app/views/children/new.html.erb, app/views/children/show.html.erb, app/views/children/show.json.jbuilder
- Explicitly setting instance variables in the controller should make
it more clear what data is being exposed to the view than using
globally available.
- Deletes unused jsbuilder views
=> Cleanup children resources

app/views/authorized_family_members/_form.html.erb
Authorized family member can be older than 10 years. This change expands birth date range.
=> Expand authorized family member date of birth range.

app/controllers/families_controller.rb, app/views/families/_family.json.jbuilder, app/views/families/edit.html.erb, app/views/families/index.html.erb, app/views/families/index.json.jbuilder, app/views/families/new.html.erb, app/views/families/show.html.erb, app/views/families/show.json.jbuilder
Equivalent to #226.
Aiming for consistency and clarity for onboarding new developers
=> Cleanup family resource

app/controllers/authorized_family_members_controller.rb, app/views/authorized_family_members/edit.html.erb, app/views/authorized_family_members/new.html.erb, app/views/authorized_family_members/show.html.erb
=> Shore up AuthorizedFamilymember resource

app/models/partner_request.rb, app/views/partner_requests/index.html.erb, spec/features/family_requests_feature_spec.rb
- Add link to pickup sheets on the partner request page.
- Add misc child item requests relationship to partner requests
=> Diaper request link to pickup sheet

app/controllers/children_controller.rb, app/models/child_item_request.rb, app/views/children/show.html.erb, spec/features/child_feature_spec.rb
walk it off
https://i.imgur.com/k4Jo9Iw.mp4
- Add details about ordered/picked up items on the child view page behind feature flag
=> Diaper request link to pickup sheet on child page

app/views/partners/_form.html.erb, app/views/partners/show.html.erb
=> Missing labels that werent added at strangeloop.

app/controllers/api/v1/partners_controller.rb, app/controllers/partners_controller.rb, app/controllers/users/invitations_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/mailers/recertification_mailer.rb, app/models/partner.rb, app/views/layouts/_navbar.html.erb, app/views/layouts/application.html.erb, app/views/partners/index.html.erb, app/views/partners/show.html.erb, app/views/shared/_flash.html.erb, app/views/users/_form.html.erb, app/views/users/index.html.erb, app/views/users/invitations/new.html.erb, config/routes.rb, db/migrate/20191022214135_add_name_to_users.rb, db/schema.rb, db/seeds.rb, spec/mailers/recertification_mailer_spec.rb, spec/models/partner_spec.rb, spec/requests/api/v1/partners_requests_spec.rb
=> Allow partners to have multiple users

app/controllers/families_controller.rb, app/models/family.rb, app/views/families/index.csv.erb, app/views/families/index.html.erb, spec/controllers/families_controller_spec.rb
Resolves #252  
With a spec testing content type request, and i created a family_controller_spec to start with new tests about what was created.
Before
Now
Csv file
=> add button to export families as a csv

app/controllers/children_controller.rb, app/models/child.rb, app/views/children/index.csv.erb, app/views/children/index.html.erb, spec/controllers/children_controller_spec.rb
Resolves #252  
With a spec testing content type request, and i created a children_controller_spec to start with new tests about what was created.
Before
Now
Csv file
=> add button to export children as csv

app/controllers/children_controller.rb, app/helpers/ui_helper.rb, app/models/child.rb, app/models/concerns/filterable.rb, app/views/children/index.html.erb, spec/features/child_feature_spec.rb
Resolves #253 
Add filter to Children resource
* Feature
Running specs
=> Add filter to Children

app/views/families/index.html.erb
Resolves #276
Issue #276 shared that there have been some requests to move the Add New Family button higher up in the page, so users wouldn't have to scroll down. This pull request resolves that issue. I moved the link_to anchor element higher up in the erb file. I also included some inline style for a little spacing around the button.
I ran the app locally. I confirmed that the link is higher up in the page and that it still works.
Note, the Add New Family button is now under the current partner name.
=> Moving the add family link higher up in the page.

spec/services/diaper_bank_client_spec.rb
This PR adds some specs to the `DiaperBankClient`
=> Adding more specs to DiaperBankClient

app/models/partner.rb, spec/models/partner_spec.rb
Work towards https://github.com/rubyforgood/diaper/issues/1623
Add support for the partner to send list of zip codes to the diaper base app.
Added more specs.
=> Work towards displaying list of zip codes in Diaper app.

db/migrate/20200518010905_add_status_in_diaper_base_to_partner.rb, db/schema.rb
=> [300] Add status_in_diaper_base To Partner Model

app/models/family.rb
Resolves https://github.com/rubyforgood/partner/issues/286 
Fixes a typo in the csv header.
I'm going to assume that a small typo change like this doesn't need a spec. I'm open to suggestions.
=> Typo fix in csv header.

app/controllers/family_requests_controller.rb, app/views/family_requests/_list.html.erb, app/views/family_requests/new.html.erb, app/views/family_requests/new.js.erb, spec/features/family_requests_feature_spec.rb
Resolves #355  
Add filtering for Family Request
* Feature
Running test with rspec
=> Add filtering for Family Request

app/controllers/families_controller.rb, app/models/family.rb, app/views/families/_list.html.erb, app/views/families/index.html.erb, app/views/families/index.js.erb, spec/features/family_feature_spec.rb
Add filter to families page
* Feature
Running tests with rspec
=> Add filter to families

app/controllers/families_controller.rb, app/helpers/application_helper.rb, app/views/families/_list.html.erb, spec/features/family_feature_spec.rb
Add sortable table to Families Page
* Feature
Running tests with rspec
=> Add sortable table to families

app/controllers/children_controller.rb, app/helpers/application_helper.rb, app/views/children/_list.html.erb, spec/features/child_feature_spec.rb
Add sortable table to Children page
* Feature
Running tests with rspec
=> Add sortable table to Children page

app/mailers/recertification_mailer.rb, app/views/recertification_mailer/notice_email.text.erb, spec/mailers/recertification_mailer_spec.rb
Resolves #383
Ran specs locally
=> Edits for recertification mailer

app/views/layouts/_navbar.html.erb
Resolves #396  
Add dropdown arrow icon to indicate that you can click the name
* Feature
=> Add dropdown arrow icon

.travis.yml, README.md, config/deploy.rb
This PR adds instructions to deploy and modify the deployment script to specifically ask for a BRANCH or TAG
Include anything else we should know about. -->
Test deployed to staging
=> Update readme with deployment instructions and deployment script

app/controllers/partner_requests_controller.rb
=> HotFix for 433

.travis.yml, README.md, ubuntu-installation.md
Last piece of changing the default branch from master -> main.
=> Update travis to deploy main, not master.

app/views/dashboard/_diaper_request_history.html.erb, app/views/family_requests/new.html.erb, app/views/individuals_requests/new.html.erb, app/views/layouts/_sidebar.html.erb, app/views/partner_requests/index.html.erb, app/views/partner_requests/new.html.erb, spec/features/child_feature_spec.rb, spec/features/family_requests_feature_spec.rb, spec/features/pickup_sheet_feature_spec.rb
=> attempted to change diaper to essential in listed places

spec/features/authorized_family_member_feature_spec.rb, spec/features/child_feature_spec.rb, spec/features/partner_approval_feature_spec.rb, spec/features/partner_edit_feature_spec.rb
- Refactor on the feature specs using old RSpec syntax and some bad practices, trying to make the specs updated with RSpec guidelines and more readable.
* Refactor
- Running RSpec suite command
=> Refactor specs

app/views/dashboard/_diaper_request_history.html.erb, app/views/dashboard/_family_details.html.erb, app/views/dashboard/_partner_details.html.erb, app/views/dashboard/index.html.erb, app/views/partner_requests/_request_card.html.erb, app/views/partner_requests/index.html.erb
Move the requests to a card and put in helpful language.
=> Requests to Card

app/assets/stylesheets/application.scss
Font awesome was being double imported which was breaking the print stylings on the pickup sheet. This PR fixes that.
=> Font awesome was being imported twice and thus messing up a stylesheet
