rubyforgood/partner

app/services/diaper_bank_client.rb
This is a very superfical change, but it was something that stuck out as I was trying to get familar with the codebase. 
Updates the check for whether or not we are in production in `DiaperBankClient.post` to use the `#production?` helper instead of checking the string `"production"`.
* Style Change 
I did a manual test in the console to make sure in development no requests are made:
```
pry(main)> DiaperBankClient.post(1)
=> nil
```
I was considering making a test that makes sure `Net::HTTP::Post.new` or something wasn't called, but it felt like it may be too brittle to provide value.
=> Updates environment check in `DiaperBankClient`.

README.md, db/seeds.rb
Resolves #52 
This updates the email addresses in the seeds to match those outlined in [diaperbase](https://github.com/rubyforgood/diaper#login). 
Tested locally by reseting the database.
=> update seeds to match what's in diaperbase readme

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/partner_requests_controller.rb, app/controllers/partners_controller.rb, app/policies/application_policy.rb, app/policies/partner_policy.rb, app/policies/partner_request_policy.rb, app/views/partner_requests/index.html.erb, app/views/partner_requests/show.html.erb, app/views/partners/show.html.erb, spec/controllers/partner_requests_controller_spec.rb
We [discussed previously in slack](https://rubyforgood.slack.com/archives/C8VC5FLQ0/p1541168645024200) the need to protect the partners information through the use of some authorization scheme. 
This adds some light weight authorization via [Pundit](https://github.com/varvet/pundit). 
**Partners**:
no one: index, destroy
anyone is authorized to: new, create
restricted to the current_partner being equal to the requested partner for:  show, edit, update
**Partner Requests**:
restricted to the current_partner being equal to the requested partner for: new, create, index, show
- RSpec tests have been slightly modified to allow for …
=> Authorization with pundit

.rubocop.yml, README.md, config/deploy/production.rb
I noticed in the README that the ruby version did not match what was in the Gemfile and .ruby-version file, so I updated it in the README, and the rubocop and prod deploy configs.
Ran the existing test suite and rubocop - all green.
=> Updates ruby version to 2.5.3 in README, rubocop, and prod deploy files

.rspec, Gemfile, Gemfile.lock, app/models/partner_request.rb, spec/controllers/partner_requests_controller_spec.rb, spec/controllers/partners_controller_spec.rb, spec/models/partner_request_spec.rb, spec/models/partner_spec.rb, spec/rails_helper.rb, spec/requests/api/v1/partners_requests_spec.rb, spec/support/controller_macros.rb, spec/support/shared_examples/user_not_logged_in.rb
Adding and updating (some refactoring) controller and model specs as outlined below (and some as requested in #51 ).  Also adds a shared example, adds [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers), and some other minor related changes as detailed below.
**NOTE:** I didn't want to add or refactor too many at once before getting feedback.
* Adds and updates PartnerRequests and Partners controller specs
* Adds a shared example for when users are not logged in
* Updates `rails_helper` configs so shared examples can be used in specs
* Adds and updates PartnerRequest and Partner model specs
* Adds `shoulda-matchers` gem and configs
* Removes explicit calls to `FactoryBot`
* Removes `dependent: :destroy` from `belongs_to :partner` in PartnerRequest model (see …
=> Adding and updating controller and model specs, and related changes

app/controllers/partner_requests_controller.rb, app/services/diaper_bank_client.rb, app/views/partner_requests/_item.html.erb, app/views/partner_requests/new.html.erb
Resolves #63 
This change attempts to resolve #63. We've added a call to the diaper app in a corresponding PR (https://github.com/rubyforgood/diaper/pull/658) to retrieve the list of items for the given organization for the partner. 
* Tested locally in browser. 
Ultimately, what I'd like to see eventually are some tests of the ( DiaperBankClient itself and perhaps some fake in place for diaper app for some integration style tests.
=> Only Show Active Items in Partner Request Form

README.md, config/database.yml
I was unable to setup my development environment since logging in without a specified hostname on my system with the database as configured results in an authentication failure. This change allows for the default of `localhost` to remain the same, but for the option to change the hostname as needed. (This pattern is the same as that used for the `diaper` app, so it should likely feel familiar here.)
(This is a minor config change, and the README has been updated to reflect it.)
One test is currently failing for me, but it seems to be a case where a prior test is not cleaning up after itself properly (or perhaps a prior run of this test). I'll look at that later, but …
=> Allow specifying database hostname via PG_HOST env var

app/views/devise/mailer/invitation_instructions.html.erb
Found while resolving https://github.com/rubyforgood/partner/issues/77
See also: https://github.com/rubyforgood/diaper/pull/708
Our community partner PDX Diaperbank reported a minor bug where placeholder text was visible to email recipients. This small change uses their suggestion to replace that placeholder text in the preheaders with the first line from the regular body. 
This only replaces text, no logic changes. 
Tested in the rails console with a factory for distribution and the following 
`User.invite!(email: 'chase@example.com', name: 'chase')`
Verified using letter_opener and inspecting the source.
=> replaces preheader with 1st line of email body

app/assets/javascripts/partner_requests.js, app/views/partner_requests/_item.html.erb
Resolves #86 
It seems that in some new theming (https://github.com/rubyforgood/partner/pull/68) that we inadvertently added a second `class` argument to the `link_to` in `app/views/partner_requests/_item.html.erb`. This caused the first `class` argument to be ignored which meant that the required `remove_record` class was missing from the button causing the JS in `partner_requests.js` to miss the click event.
Tested in browser locally. 
See attached gif.
=> fix line item removal bug

app/views/devise/mailer/invitation_instructions.html.erb
Resolves #80 
There were two actions in this issue: I have completed one of them; the two spelling mistakes in the email body text. 
I need help on the other, which was to remove or change the placeholder (preheader) text showing on the email preview subject line. Right now, I can't find this text in the codebase. Also, I don't know how to replicate this problem (sending myself an email) to see if I've fixed it. I would really appreciate your advice (more details below if required). Thank you! ❤️ 
I can see in `/app/views/mailer/invitation_instructions.html.erb`there is a class called "preheader", which has been assigned the text "You've been invited to become a partner organization." (line 335). I could hypothesise that this is the text which _should_ be showing in the preview subject …
=> Spelling corrections partner invitation email

config/initializers/01_constants.rb
Resolves #85 
Referencing rubyforgood/diaper#630 where we added a new cannonical item for X-Small/Small Adult Briefs. We have therefore updated the hash of POSSIBLE_ITEMS to include this brief size.
=> added xs adult brief size to hash

app/views/partners/_form.html.erb, config/initializers/01_constants.rb, spec/features/partner_edit_feature_spec.rb
Resolves #75 
We have created a dropdown box allowing agency users to choose which of the National Diaper Bank Network's classifications their agency falls into.
We did this by adding the NDBN's Agency Type classifications to the list of constants in the initialisers directory. 
We then added a helper method to the form to create a dropdown. 
_This issue will be fully resolved when we have learnt whether the "other" classification requires a description from the agency user, as suggested in the excel spreadsheet supplied._
We tested this by submitting the form and checking in the rails console that the database had attributed this new item of information to the partner.
It would also be good to know (for my learning in …
=> Add NDBN agency type classification drop down form

app/controllers/api/v1/partners_controller.rb, app/controllers/partner_requests_controller.rb, app/helpers/application_helper.rb, app/views/partners/show.html.erb, db/schema.rb, db/seeds.rb, spec/controllers/partner_requests_controller_spec.rb, spec/factories/partner_factory.rb, spec/requests/api/v1/partners_requests_spec.rb, spec/support/controller_macros.rb
Related to https://github.com/rubyforgood/diaper/pull/820
and https://github.com/rubyforgood/diaper/issue/773
Here, we are making changes to allow for the recertification partner flow. 
This includes updating partner status from that status saved on `diaper`. This also includes showing the partner status and restricting new diaper requests if the partner status is not approved. 
- This has been tested by the automated test suite
- This has been tested manually with a local running copy of diaper
=> Corresponding changes for use with Diaper PR#820 - Partner Re-certification

Gemfile, Gemfile.lock
Bootstrap version < 4.3.1
Ref: https://nvd.nist.gov/vuln/detail/CVE-2019-8331
Devise version < 4.6.0
Ref: https://github.com/plataformatec/devise/issues/4981
Test were run against the newly installed dependencies, and the app was loaded in my local browser to ensure that no visual regression occurred as a result of the bootstrap gem upgrade.
=> Update gems with security vulnerabilites

Gemfile, Gemfile.lock, app/assets/javascripts/partners.js, app/controllers/partners_controller.rb, app/models/partner.rb, app/views/partners/_form.html.erb, app/views/partners/show.html.erb, db/migrate/20190315202706_add_other_agency_type_to_partners.rb, spec/features/partner_edit_feature_spec.rb, spec/rails_helper.rb
Resolves #92 
@chaserx and I added a text input field into the partner agency form so that users can describe their agency type if they choose to identify as "Other" from the NDBA agency type list. This is then committed to the database.
We tested this in the rails console, but need to add a test in the spec directory and will do this shortly.
=> Add other agency type input into form and attribute in database

app/assets/stylesheets/bootstrap.min.css, app/controllers/children_controller.rb, app/controllers/families_controller.rb, app/models/child.rb, app/models/family.rb, app/models/partner.rb, app/views/children/_form.html.erb, app/views/children/show.html.erb, app/views/families/_form.html.erb, app/views/families/show.html.erb, db/migrate/20190721044143_add_archived_to_child.rb, db/schema.rb, spec/factories/children.rb, spec/factories/families.rb
This is almost entirely a formatting/copy fix. This PR changes the language used on the various fields on the children/families pages to match what the diaper banks wanted. 
There is a single migration to add an additional field `archived` to the children to denote when they age out of being able to receive diapers but they want to keep their info in the system for historical/reporting data. I'll likely create another Issue (and PR?) to ensure that archived kids don't show up in the family request list.
=> Clean up the wording, input and so on of the family and children fields.

app/controllers/api/v1/partners_controller.rb, config/routes.rb, spec/requests/api/v1/partners_requests_spec.rb
This increases the test coverage for the Partner API. Specifically, it adds tests for each status change. 
There's also some minor cleanup to the routes to reflect how we're using the routes currently and to the response that we provide on partner update. 
* tests run/pass locally
* CI
* **should verify that the client applications still work**
=> Add status changing tests to partner request spec

app/controllers/api/v1/partners_controller.rb, app/controllers/partner_requests_controller.rb, app/helpers/application_helper.rb, app/models/partner.rb, app/views/partners/show.html.erb, db/seeds.rb, spec/controllers/partner_requests_controller_spec.rb, spec/factories/partner.rb, spec/features/partner_approval_feature_spec.rb, spec/models/partner_spec.rb, spec/requests/api/v1/partners_requests_spec.rb
Resolves #001 
We had a bug in which the partner approval button was looking for a `partner_status` of `recertification_requested`, but the status was passed inconsistently.
This led to attempting to force an enum of all partner statuses, which is ongoing.
See new spec: `spec/features/partner_approval_feature_spec.rb`
=> Refactor app to use consistent partner statuses

db/seeds.rb, spec/lib/tasks/db_seed_spec.rb
Resolves #162 
- No longer references email and password attributes on the Partner model during database seeding
- Cleans up duplicate name attribute
Ran `db:seed` task successfully
=> Fix seeds file

app/views/devise/invitations/edit.html.erb, config/environments/development.rb, config/routes.rb
One of our diaper bank users pointed out that we do not have any sylings on the invitation page. This simple PR fixes that and adds styling.
Before:
After:
=> Invitation Page Styling

app/views/partners/_form.html.erb, app/views/partners/show.html.erb
Resolves #197 #198 
Moved Internal Database section from the Population Served section to the Agency Stability section, before the Evidence Based section. 
This change occurs in `views/partners/_form.html.erb` per #197 and `views/partners/show.html.erb` per #198 
Requested change via Issues to provide greater clarity in the overall form.
Relocation of section. Visual confirmation of relocation.
=> Moved Internal Database Section, Issues #197 & #198

app/models/family_request.rb, spec/models/family_request_spec.rb
Add new spec to test FamilyRequest for more test coverage
* Improvement
Running specs
=> Add spec to family_request.rb

Gemfile.lock
Addresses [CVE-2019-16109]
[CVE-2019-16109]: https://nvd.nist.gov/vuln/detail/CVE-2019-16109
=> [security] Update devise to 4.7.1

Gemfile.lock
Addresses [CVE-2019-5477]
[CVE-2019-5477]: https://nvd.nist.gov/vuln/detail/CVE-2019-5477
=> [security] Update nokogiri to 1.10.4

Gemfile.lock
Addresses [CVE-2019-16892]
[CVE-2019-16892]: https://nvd.nist.gov/vuln/detail/CVE-2019-16892
=> [security] Update rubyzip to 1.3.0

app/assets/stylesheets/application.scss, app/controllers/child_item_requests_controller.rb, app/views/child_item_requests/_child_item_request_update.js.erb, app/views/pickup_sheets/show.html.erb
Make marking pickup  more intuitive by flipping row background color when pickup is marked as picked up.
=> flip child item request backgorund color

config/locales/en.yml, spec/features/pickup_sheet_feature_spec.rb
Add more comprehensive specs for pickup sheets. We now test every ajax request and that the flash message is displayed correctly.
=> Add more comprehensive specs for pickup sheets.

README.md, spec/rails_helper.rb
- Remove duplicate config
- Document how to run specs in the browser
=> Document how to run feature specs in headless mode or in the browser.

spec/factories/children.rb
Fixes a deprecation warning that appears when running the specs. The following appeared before:
`partner/spec/factories/children.rb:28: Passing 'days' with the 1st argument of 'backward' is deprecated. Use keyword argument like 'backward(days: ...)' instead.`
* Test Suite Only
Just re-running the test suite. After I made the update and re-ran the specs, the deprecation warning was gone
=> fix deprecation warning inside factory file

app/views/families/show.html.erb
Resolves #250 
There was no area for children information on family show page. Also card's were using wrong div class. Changed them to class="card mb-4"
Tested by view
=> Add children info to families show page

app/views/partner_requests/index.html.erb
Sean and I had talked about this at the conference.
I noticed it while demoing the app to some attendees. This PR moves the create new request buttons to the top of the requests #index page.
I wasn't sure how to style it; we don't really have this anywhere else yet. Happy to change it if there's a preferred styling!
=> Moves the create buttons to the top of the request index

app/views/children/index.html.erb
Resolves #282  
* Just add bootstrap class to add margin top
* This change does not requires a documentation update
* Style change
BEFORE:
AFTER:
=> Add margin top to filters buttons in children index

app/controllers/api/v1/add_partners_controller.rb, app/controllers/api/v1/partners_controller.rb, app/mailers/custom_devise_mailer.rb, app/models/user.rb, config/initializers/devise.rb
Resolves https://github.com/rubyforgood/partner/issues/290
We want to be able to set the `reply_to` field of Invitation emails to the organization's email instead of the generic `accounts@diaper.app` email. This way organizations can service issues presented by partners quicker without engineering intervention.
This PR accepts the `organization_email` contained in API requests (added in https://github.com/rubyforgood/diaper/pull/1610) and sets the reply_to to that field. The way this PR does it is by adding a custom devise mailer that can set the `reply_to` to the attr on User called `invitation_reply_to`.
- Add CustomDeviseMailer to change `reply_to`
- Add `invitation_reply_to` to User
- Modify API endpoint to utilize the `organization_email` provided.
**Blocked by …
=> Set Invitation reply_to to organzation email that invited the partner

Gemfile.lock
Forgot to update the Gemfile.lock from merging in https://github.com/rubyforgood/partner/pull/296
=> Fix Gemfile.lock by removing unneccesary gems mentioned

db/seeds.rb
I noticed that when trying to seed my database with `ChildItemRequest` the section to create them in the seed file fails silently. With a closer look I noticed that this validation error occurs:
```
ActiveRecord::RecordInvalid: Validation failed: Child must exist
from /Users/edwinmak/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/validations.rb:80:in `raise_validation_erro
``` 
A simple fix is to add `.id` to the `Child.all.sample` as shown in the PR.
Ran it locally before and after
=> Properly seed ChildItemRequest from db/seeds

app/controllers/application_controller.rb, app/views/children/show.html.erb, spec/features/child_feature_spec.rb
Resolves #329
I noticed that the use of `.dig` to retrieve the item name from `valid_items` in the `child#show` template was pulling the wrong record. The format of `valid_items` is an array of hashes so the correct approach should be the `find` and then retrieve the name.
Format of `valid_items`:
```
[{"id"=>11, "partner_key"=>"k_preemie", "name"=>"Kids (Preemie)"},
{"id"=>13, "partner_key"=>"k_size2", "name"=>"Kids (Size 2)"},
{"id"=>18, "partner_key"=>"k_size7", "name"=>"Kids (Size 7)"},
{"id"=>19, "partner_key"=>"k_lxl", "name"=>"Kids L/XL (60-125 lbs)"},
{"id"=>20, "partner_key"=>"pullup_23t", "name"=>"Kids Pull-Ups (2T-3T)"},
{"id"=>21, "partner_key"=>"pullup_34t", "name"=>"Kids Pull-Ups (3T-4T)"},
{"id"=>23, "partner_key"=>"k_sm", "name"=>"Kids S/M (38-65 lbs)"},
{"id"=>24, …
```
=> Properly fetch valid item name in child#show

.env.test, app/controllers/api/v1/add_partners_controller.rb, app/controllers/api/v1/partner_forms_controller.rb, app/controllers/api/v1/partners_controller.rb, app/controllers/api_controller.rb, spec/requests/api/v1/add_partners_requests_spec.rb, spec/requests/api/v1/partner_forms_requests_spec.rb, spec/requests/api/v1/partners_requests_spec.rb
Resolves #99 
- Adds tests to all V1 API request specs to assert:
+ 403 is returned when an invalid API key is used
+ 403 is returned when the `DIAPER_KEY` environment variable is not set
- Moves the `api_key_valid?` method to the parent `ApiController`
- Rejects API requests if the `DIAPER_KEY` environment variable is not set
* Breaking change if `DIAPER_KEY` environment variable is not set in production
- Add automated tests to reflect each change
=> Add API key tests to API requests specs and rejects requests if env var not set

app/views/dashboard/_family_details.html.erb, spec/features/dashboard_feature_spec.rb
Resolves #344 
- Ensures only unique "Areas Served" zip codes are displayed on the dashboard
- Introduced a `dashboard_feature_spec`
=> Display unique areas served zip codes on partner dashboard

spec/requests/api/v1/partners_requests_spec.rb
This PR adds missing specs to cover the cases in which the `impact_metric` query parameter is provided or not provided.
* Adding Spec
=> Add missing specs for behavior of partners#show

app/controllers/api/v1/partners_controller.rb, spec/requests/api/v1/partners_requests_spec.rb
This PR prevents raising an error due to trying to access a method on `nil` if the id provided to partners#show doesn't match any partner. Instead this PR will raise an error early and also return status code `not_found` if there is no `Partner` that matches the id provided.
I discovered this from trying to troubleshoot this error (below) from a contributor of the diaper repo.
By raising an error earlier via this PR, I get a slightly better error message:
Ideally, this sort of error gracefully fails. But for now, I think this PR makes the error clearer and easier to pinpoint the source of the issue (aka in this case the id doesn't match any Partner in the partner db)
- Added a spec that covers this case.
=> Trigger raise in partners#show instead of accessing nil error

spec/controllers/children_controller_spec.rb, spec/rails_helper.rb
Resolves #151 
Add new spec to test ChildrenController
* Improvement
Running specs
=> Add spec to ChildrenController

app/controllers/children_controller.rb, app/controllers/families_controller.rb, app/controllers/family_requests_controller.rb
Resolves #395
Our partner users are getting confused because they are unable to scroll through all their children, family, or family request records. This was due to the addition of `.pagination` which forced the results to be limited to 25 records. Normally pagination would be great, but we are missing buttons to navigate between pagination pages and it seems to be a larger lift to change that behavior.
I think we should introduce pagination again when performance becomes an issue. However, for now I suggest we just remove it until we get to that point.
1. Login as a partner
2. Access the pages changed and ensure you are seeing all the records rather than just 25
=> Prevent hiding children, family, and family request list results due to pagination

app/views/children/_list.html.erb, app/views/children/index.html.erb, app/views/families/_list.html.erb, app/views/families/index.html.erb
A bug report was made by a Partner who stated:
>The CSV files are only pulling the Families or Children that I can see on the first page, none of the other are being picked up.
This is because the filter affects the content of the CSV and it very clear that is happening. This PR does two things:
- Changes the text from "Export a CSV file" to "Export Results To CSV". This indicates the current results is what will be in the CSV.
- Move the button to the table to relate the CSV button to the results spatially.
1. Login as a partner
2. Click "Export Results To CSV" and download the results.
=> Update export csv button in families & children to be indicative of what it will generate

app/views/layouts/_navbar.html.erb
Resolves #403
Instead of rendering the nonexistent `name` on User records, this PR renders the email which does exist on User records.
=> Render email instead of non existent name on User for dropdown button

app/controllers/family_requests_controller.rb, app/views/family_requests/_list.html.erb, spec/requests/family_requests_controller_spec.rb
This PR addresses a bug in which a 500 error occurs when submitting a family request that has a child without a defined item that they need. The way this PR achieves is it is by modifying the query to skip sending a payload with children w/o items in need. In addition, it includes a UI change to hide the active toggle if the item isn't defined.
Built a request spec for this :)
=> Prevent error caused by family request without defined item for children.

.rubocop.yml, app/models/partner.rb, app/models/partner_form.rb
Resolves #436 
Config file now matches that of the Diaper repo. Only `Style/ArrayCoercion` was newly added. Took the initiative to remove some redundant cop disabling for `Rails/UniqueValidationWithoutIndex` since it is now defaulted to being disabled on the config file.
No Rubocop offenses
All tests still pass
=> Add rubocop defaults to config file
